package main

// Game State Integration: CS2 can POST live match state (score, round,
// phase) to an HTTP endpoint. RCON cannot report any of that, so this is
// the only way to show a real scoreboard. It is opt-in: the user has to
// drop a small cfg file on the server, generated by GSIConfigFile below.

import (
	"encoding/json"
	"fmt"
	"net"
	"net/http"
	"sync"
	"time"
)

type GameState struct {
	Live      bool   `json:"live"` // data arrived recently
	Map       string `json:"map"`
	Mode      string `json:"mode"`
	Phase     string `json:"phase"`      // warmup, live, intermission, gameover
	RoundNum  int    `json:"roundNum"`   // rounds played
	RoundPh   string `json:"roundPhase"` // freezetime, live, over
	Bomb      string `json:"bomb"`
	ScoreCT   int    `json:"scoreCt"`
	ScoreT    int    `json:"scoreT"`
	UpdatedAt int64  `json:"updatedAt"`
}

type GSI struct {
	mu     sync.Mutex
	state  GameState
	server *http.Server
	port   int
}

// payload mirrors the parts of the CS2 GSI JSON we display.
type payload struct {
	Map struct {
		Mode   string `json:"mode"`
		Name   string `json:"name"`
		Phase  string `json:"phase"`
		Round  int    `json:"round"`
		TeamCT struct {
			Score int `json:"score"`
		} `json:"team_ct"`
		TeamT struct {
			Score int `json:"score"`
		} `json:"team_t"`
	} `json:"map"`
	Round struct {
		Phase string `json:"phase"`
		Bomb  string `json:"bomb"`
	} `json:"round"`
}

func NewGSI() *GSI { return &GSI{} }

// Start listens on the given port. Port 0 disables GSI.
func (g *GSI) Start(port int) error {
	g.Stop()
	if port <= 0 {
		return nil
	}
	mux := http.NewServeMux()
	mux.HandleFunc("/", g.handle)
	srv := &http.Server{Addr: fmt.Sprintf(":%d", port), Handler: mux}

	ln, err := net.Listen("tcp", srv.Addr)
	if err != nil {
		return err
	}
	g.mu.Lock()
	g.server, g.port = srv, port
	g.mu.Unlock()
	go srv.Serve(ln)
	return nil
}

func (g *GSI) Stop() {
	g.mu.Lock()
	srv := g.server
	g.server = nil
	g.mu.Unlock()
	if srv != nil {
		srv.Close()
	}
}

func (g *GSI) handle(w http.ResponseWriter, r *http.Request) {
	var p payload
	if err := json.NewDecoder(r.Body).Decode(&p); err == nil && p.Map.Name != "" {
		g.mu.Lock()
		g.state = GameState{
			Map:       p.Map.Name,
			Mode:      p.Map.Mode,
			Phase:     p.Map.Phase,
			RoundNum:  p.Map.Round,
			RoundPh:   p.Round.Phase,
			Bomb:      p.Round.Bomb,
			ScoreCT:   p.Map.TeamCT.Score,
			ScoreT:    p.Map.TeamT.Score,
			UpdatedAt: time.Now().Unix(),
		}
		g.mu.Unlock()
	}
	w.WriteHeader(http.StatusOK)
}

// State returns the last received state, marked Live when it is recent.
func (g *GSI) State() GameState {
	g.mu.Lock()
	defer g.mu.Unlock()
	s := g.state
	s.Live = s.UpdatedAt > 0 && time.Now().Unix()-s.UpdatedAt < 30
	return s
}

// localIPFor returns the address of the interface used to reach the server,
// so the generated config points back at this machine.
func localIPFor(host string, port int) string {
	conn, err := net.DialTimeout("tcp", fmt.Sprintf("%s:%d", host, port), 3*time.Second)
	if err != nil {
		return "<your-pc-ip>"
	}
	defer conn.Close()
	if addr, ok := conn.LocalAddr().(*net.TCPAddr); ok {
		return addr.IP.String()
	}
	return "<your-pc-ip>"
}

// GSIConfigFile builds the cfg the user copies to the server, filled in
// with the address this machine is reachable at.
func GSIConfigFile(ip string, port int) string {
	return fmt.Sprintf(`"StrikeMan"
{
	"uri"       "http://%s:%d/"
	"timeout"   "5.0"
	"buffer"    "0.1"
	"throttle"  "0.5"
	"heartbeat" "10.0"
	"data"
	{
		"provider" "1"
		"map"      "1"
		"round"    "1"
	}
}
`, ip, port)
}
