// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {config} from '../models';

export function AddBot():Promise<void>;

export function Announce(arg1:string):Promise<void>;

export function ApplyPreset(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function ChangeMap(arg1:string,arg2:boolean):Promise<void>;

export function CheckForUpdate():Promise<app.UpdateInfo>;

export function EndWarmup():Promise<void>;

export function ExportServers(arg1:Array<app.PortableServer>,arg2:string):Promise<string>;

export function GetActiveServer():Promise<string>;

export function GetActiveServerConfig():Promise<app.ServerView>;

export function GetAppVersion():Promise<string>;

export function GetConfig():Promise<config.Config>;

export function GetLanguage():Promise<string>;

export function GetMaps():Promise<app.MapList>;

export function GetPresets():Promise<Array<app.Preset>>;

export function GetServerInfo():Promise<app.ServerInfo>;

export function GetStatus():Promise<app.Status>;

export function GetToggles():Promise<Array<app.Toggle>>;

export function ImportServers(arg1:string):Promise<Array<config.Server>>;

export function InstallUpdate():Promise<void>;

export function KickBots():Promise<void>;

export function KickPlayer(arg1:string):Promise<void>;

export function Pause():Promise<void>;

export function RemoveBot():Promise<void>;

export function RestartRound():Promise<void>;

export function RunCommand(arg1:string):Promise<string>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function ScrambleTeams():Promise<void>;

export function SelectServer(arg1:string):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetTeamNames(arg1:string,arg2:string):Promise<void>;

export function SetToggle(arg1:string,arg2:boolean):Promise<void>;

export function SetWarmupSeconds(arg1:number):Promise<void>;

export function StartWarmup(arg1:number):Promise<void>;

export function SwapTeams():Promise<void>;

export function TestServer(arg1:string,arg2:number,arg3:string):Promise<string>;

export function Unpause():Promise<void>;
