// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBot() {
  return window['go']['app']['App']['AddBot']();
}

export function Announce(arg1) {
  return window['go']['app']['App']['Announce'](arg1);
}

export function ApplyPreset(arg1, arg2, arg3) {
  return window['go']['app']['App']['ApplyPreset'](arg1, arg2, arg3);
}

export function ChangeMap(arg1, arg2) {
  return window['go']['app']['App']['ChangeMap'](arg1, arg2);
}

export function CheckForUpdate() {
  return window['go']['app']['App']['CheckForUpdate']();
}

export function EndWarmup() {
  return window['go']['app']['App']['EndWarmup']();
}

export function ExportServers(arg1, arg2) {
  return window['go']['app']['App']['ExportServers'](arg1, arg2);
}

export function GetActiveServer() {
  return window['go']['app']['App']['GetActiveServer']();
}

export function GetActiveServerConfig() {
  return window['go']['app']['App']['GetActiveServerConfig']();
}

export function GetAppVersion() {
  return window['go']['app']['App']['GetAppVersion']();
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function GetLanguage() {
  return window['go']['app']['App']['GetLanguage']();
}

export function GetMaps() {
  return window['go']['app']['App']['GetMaps']();
}

export function GetPresets() {
  return window['go']['app']['App']['GetPresets']();
}

export function GetServerInfo() {
  return window['go']['app']['App']['GetServerInfo']();
}

export function GetStatus() {
  return window['go']['app']['App']['GetStatus']();
}

export function GetToggles() {
  return window['go']['app']['App']['GetToggles']();
}

export function ImportServers(arg1) {
  return window['go']['app']['App']['ImportServers'](arg1);
}

export function InstallUpdate() {
  return window['go']['app']['App']['InstallUpdate']();
}

export function KickBots() {
  return window['go']['app']['App']['KickBots']();
}

export function KickPlayer(arg1) {
  return window['go']['app']['App']['KickPlayer'](arg1);
}

export function Pause() {
  return window['go']['app']['App']['Pause']();
}

export function RemoveBot() {
  return window['go']['app']['App']['RemoveBot']();
}

export function RestartRound() {
  return window['go']['app']['App']['RestartRound']();
}

export function RunCommand(arg1) {
  return window['go']['app']['App']['RunCommand'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['app']['App']['SaveConfig'](arg1);
}

export function ScrambleTeams() {
  return window['go']['app']['App']['ScrambleTeams']();
}

export function SelectServer(arg1) {
  return window['go']['app']['App']['SelectServer'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['app']['App']['SetLanguage'](arg1);
}

export function SetTeamNames(arg1, arg2) {
  return window['go']['app']['App']['SetTeamNames'](arg1, arg2);
}

export function SetToggle(arg1, arg2) {
  return window['go']['app']['App']['SetToggle'](arg1, arg2);
}

export function SetWarmupSeconds(arg1) {
  return window['go']['app']['App']['SetWarmupSeconds'](arg1);
}

export function StartWarmup(arg1) {
  return window['go']['app']['App']['StartWarmup'](arg1);
}

export function SwapTeams() {
  return window['go']['app']['App']['SwapTeams']();
}

export function TestServer(arg1, arg2, arg3) {
  return window['go']['app']['App']['TestServer'](arg1, arg2, arg3);
}

export function Unpause() {
  return window['go']['app']['App']['Unpause']();
}
