// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBot(arg1) {
  return window['go']['main']['App']['AddBot'](arg1);
}

export function Announce(arg1) {
  return window['go']['main']['App']['Announce'](arg1);
}

export function ApplyPreset(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplyPreset'](arg1, arg2, arg3);
}

export function ChangeMap(arg1, arg2) {
  return window['go']['main']['App']['ChangeMap'](arg1, arg2);
}

export function EndWarmup() {
  return window['go']['main']['App']['EndWarmup']();
}

export function GetActiveServer() {
  return window['go']['main']['App']['GetActiveServer']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetGSISetup() {
  return window['go']['main']['App']['GetGSISetup']();
}

export function GetGameState() {
  return window['go']['main']['App']['GetGameState']();
}

export function GetMaps() {
  return window['go']['main']['App']['GetMaps']();
}

export function GetPresets() {
  return window['go']['main']['App']['GetPresets']();
}

export function GetServerInfo() {
  return window['go']['main']['App']['GetServerInfo']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function KickBots() {
  return window['go']['main']['App']['KickBots']();
}

export function KickPlayer(arg1) {
  return window['go']['main']['App']['KickPlayer'](arg1);
}

export function Pause() {
  return window['go']['main']['App']['Pause']();
}

export function RestartRound() {
  return window['go']['main']['App']['RestartRound']();
}

export function RunCommand(arg1) {
  return window['go']['main']['App']['RunCommand'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function ScrambleTeams() {
  return window['go']['main']['App']['ScrambleTeams']();
}

export function SelectServer(arg1) {
  return window['go']['main']['App']['SelectServer'](arg1);
}

export function SetTeamNames(arg1, arg2) {
  return window['go']['main']['App']['SetTeamNames'](arg1, arg2);
}

export function SetToggle(arg1, arg2) {
  return window['go']['main']['App']['SetToggle'](arg1, arg2);
}

export function StartWarmup(arg1) {
  return window['go']['main']['App']['StartWarmup'](arg1);
}

export function SwapTeams() {
  return window['go']['main']['App']['SwapTeams']();
}

export function Unpause() {
  return window['go']['main']['App']['Unpause']();
}
