// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddBot():Promise<void>;

export function Announce(arg1:string):Promise<void>;

export function ApplyPreset(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function ChangeMap(arg1:string,arg2:boolean):Promise<void>;

export function EndWarmup():Promise<void>;

export function GetActiveServer():Promise<string>;

export function GetActiveServerConfig():Promise<main.ServerView>;

export function GetConfig():Promise<main.Config>;

export function GetLanguage():Promise<string>;

export function GetMaps():Promise<main.MapList>;

export function GetPresets():Promise<Array<main.Preset>>;

export function GetServerInfo():Promise<main.ServerInfo>;

export function GetStatus():Promise<main.Status>;

export function GetToggles():Promise<Array<main.Toggle>>;

export function KickBots():Promise<void>;

export function KickPlayer(arg1:string):Promise<void>;

export function Pause():Promise<void>;

export function RemoveBot():Promise<void>;

export function RestartRound():Promise<void>;

export function RunCommand(arg1:string):Promise<string>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function ScrambleTeams():Promise<void>;

export function SelectServer(arg1:string):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetTeamNames(arg1:string,arg2:string):Promise<void>;

export function SetToggle(arg1:string,arg2:boolean):Promise<void>;

export function SetWarmupSeconds(arg1:number):Promise<void>;

export function StartWarmup(arg1:number):Promise<void>;

export function SwapTeams():Promise<void>;

export function Unpause():Promise<void>;
